name: build

on:
  push:
    branches:
      - feature/**
      - sandbox/**
  pull_request:
    branches:
      - main
      - dev
      - dev/**
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: generate .env files
      run: |
        echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
    - name: install
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: npm run install:all
      env:
        CI: true
    - name: build
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: npm run build
      env:
        CI: true
    - name: test
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: npm run test
      env:
        CI: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
