name: build

on:
  push:
    branches:
      - feature/**
      - sandbox/**
  pull_request:
    branches:
      - master
      - dev
      - dev/**
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: generate .env files
      run: echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
    - name: yarn install
      run: |
        yarn install
        npm --prefix functions ci
      env:
        CI: true
    - name: build
      run: yarn build
      env:
        CI: true
    - name: rebuild
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: yarn install --force
      env:
        CI: true
    - name: test
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: yarn test
      env:
        CI: true
