name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: generate .env files
      run: |
        echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
    - name: install
      run: npm run install:all
      env:
        CI: true
    - name: build
      run: npm run build
      env:
        CI: true
    - name: Firebase deploy
      run: |
        npx firebase use release --token ${{ secrets.FIREBASE_TOKEN }}
        npx firebase deploy --only hosting,firestore,functions --token ${{ secrets.FIREBASE_TOKEN }}
