name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: generate .env files
      run: |
        echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
        ls -al
        cat .env
    - name: npm install, build, and test
      run: |
        npm ci
        npm --prefix functions ci
        npm run build
        npm run test:unit
      env:
        CI: true
    - name: Firebase deploy
      run: |
        ./node_modules/.bin/firebase use release --token ${{ secrets.FIREBASE_TOKEN }}
        ./node_modules/.bin/firebase deploy --only hosting,firestore,functions --token ${{ secrets.FIREBASE_TOKEN }}
