name: nightly

on:
  schedule:
  - cron: 0 14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: generate .env files
      run: |
        echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
    - name: npm install
      run: |
        npm ci
        npm --prefix functions ci
      env:
        CI: true
    - name: build
      run: npm run build
      env:
        CI: true
    - name: rebuild
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: npm rebuild
      env:
        CI: true
    - name: test
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: npm run test
      env:
        CI: true
