name: nightly

on:
  schedule:
  - cron: 0 14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: generate .env files
      run: |
        echo -e ${{ secrets.FIREBASE_ENV_SETTINGS }} > .env
    - name: install
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: yarn install:all
      env:
        CI: true
    - name: build
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: yarn build
      env:
        CI: true
    - name: test
      uses: docker://oichan/firebase-emulator-docker:latest
      with:
        args: yarn test
      env:
        CI: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
